// ==========================================
// THE ULTIMATE CATEGORY LIST (Balanced & Global)
// ==========================================
export const INITIAL_CATEGORIES = [
  {
    name: 'Maintenance & Repairs',
    description: 'Expert handymen for home and office repairs',
    icon: '🔧',
    color: '#8B5CF6',
    skills: ['Electrical', 'Plumbing', 'Carpentry', 'Painting', 'AC Repair'],
    keywords: ['repair', 'handyman', 'home', 'fix', 'electrician'],
    order: 0,
  },
  {
    name: 'Cleaning & Sanitation',
    description: 'Professional cleaning for residential and commercial spaces',
    icon: '🧹',
    color: '#06B6D4',
    skills: ['Deep Cleaning', 'Office Cleaning', 'Disinfection', 'Window Washing'],
    keywords: ['cleaning', 'maid', 'janitorial', 'sanitation', 'housekeeping'],
    order: 1,
  },
  {
    name: 'Software & Tech',
    description: 'Full-stack development and technical support',
    icon: '💻',
    color: '#10B981',
    skills: ['Web Dev', 'IT Support', 'Mobile Apps', 'Cybersecurity', 'Cloud'],
    keywords: ['programming', 'developer', 'it', 'software', 'tech'],
    order: 2,
  },
  {
    name: 'Creative & Design',
    description: 'Visual arts, branding, and digital design',
    icon: '🎨',
    color: '#F59E0B',
    skills: ['Graphic Design', 'UI/UX', 'Logo Design', 'Video Editing', 'Illustration'],
    keywords: ['design', 'creative', 'art', 'branding', 'visual'],
    order: 3,
  },
  {
    name: 'Consulting & Business',
    description: 'Professional advice and administrative support',
    icon: '💼',
    color: '#EF4444',
    skills: ['Business Strategy', 'Accounting', 'Legal', 'Marketing', 'Virtual Assistant'],
    keywords: ['consultant', 'advisor', 'finance', 'management', 'admin'],
    order: 4,
  },
  {
    name: 'Education & Tutoring',
    description: 'Academic help and skill training',
    icon: '📚',
    color: '#EC4899',
    skills: ['Languages', 'Math', 'Coding Lessons', 'Music', 'Test Prep'],
    keywords: ['teacher', 'tutor', 'classes', 'learning', 'education'],
    order: 5,
  },
  {
    name: 'Logistics & Transport',
    description: 'Moving, delivery, and personal transportation',
    icon: '🚚',
    color: '#6366F1',
    skills: ['Moving', 'Courier', 'Trucking', 'Personal Driver', 'Freight'],
    keywords: ['delivery', 'transport', 'shipping', 'moving', 'logistics'],
    order: 6,
  },
  {
    name: 'Events & Hospitality',
    description: 'Event planning and service staff',
    icon: '🎉',
    color: '#14B8A6',
    skills: ['Catering', 'Photography', 'DJ/Music', 'Waitstaff', 'Decorating'],
    keywords: ['party', 'event', 'wedding', 'staff', 'catering'],
    order: 7,
  },
  {
    name: 'Beauty & Wellness',
    description: 'Personal care and health services',
    icon: '💇',
    color: '#D946EF',
    skills: ['Hair Styling', 'Massage', 'Personal Training', 'Makeup', 'Skincare'],
    keywords: ['beauty', 'spa', 'health', 'fitness', 'barber'],
    order: 8,
  }
];